Repository skycoin/hardware-wallet-js, pull requests merged in 2019-04, with the labels that each got.

#95 [ci] fixes #94 - Run eslint --fix in npm format
  package.json
Labels: stdev, wip

#92 [test] fixes #74 - Refactor promises in test code
  .travis.yml
  Makefile
  package.json
  test/applySettings-test.js
  test/cancel-request-test.js
  test/device-backup-test.js
  test/messages-test.js
  test/sign-test.js
  utils.js
Labels: Milestone v.1.0.0, stdev, wip

#104 fixes #103 - Document firmware features
  .github/pull_request_template.md
  DOCUMENTATION.md
Labels: Milestone v.1.0.0, doc, stdev, wip
