Repository skycoin/hardware-wallet-js, pull requests merged in 2019-05, with the labels that each got.

#115 [device-wallet] fixes #114 - Button ACK in SkycoinSign message
  device-wallet.js
Labels: Milestone v.1.0.0, ci, stdev, wip

#116 Add test for memprotect firmware feature
  device-wallet.js
  test/memoryProtection-test.js
Labels: Milestone v.1.0.0, stdev, wip

#121 Send the deviceHandle.close callback instead of the function result ref #110
  device-wallet.js
Labels: stdev, wip
